<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerZhqpj36\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerZhqpj36/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerZhqpj36\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZhqpj36\appDevDebugProjectContainer();
